---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.lidarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.lidarr'

- name: 'Converge | toggle SSL'
  hosts: 'lidarr-debian-12-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle SSL | apply r_pufky.srv.lidarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.lidarr'
      vars:
        lidarr_cfg_enable_ssl: false
