---
- name: 'Live API test | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Live API test | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Live API test | verify | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Live API test | verify | config.xml'
        test_src: 'files/config.xml'
        test_file: '/var/lib/lidarr/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'

    # Lidarr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Live API test | verify | assert lidarr.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"lidarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["lidarr.service"]["state"] == "running"'
        fail_msg: 'lidarr.service should be enabled and running.'

    - name: 'Live API test | verify | /var/lib/lidarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/lidarr'
        test_file: '/var/lib/lidarr'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0775'
        test_state: 'directory'

    - name: 'Live API test | verify | /var/lib/lidarr/update_script'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/lidarr/update_script'
        test_file: '/var/lib/lidarr/update_script'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Live API test | verify | /var/lib/lidarr/lidarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /var/lib/lidarr/lidarr.pfx'
        test_file: '/var/lib/lidarr/lidarr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'

    - name: 'Live API test | verify | /data/media'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Live API test | verify | /data/media'
        test_file: '/data/media'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0755'
        test_state: 'directory'
