---
###############################################################################
# Configure Services
###############################################################################
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result.
#
# MediaCover (metadata) directory is Multi-GB. Safe to delete but will cause
# large metadata downloads on new version if not migrated with databases.
# Exclude from removal during configuration sync.

- name: 'Config | filetree | set managed directories'
  ansible.builtin.file:
    path: '{{ lidarr___app._var_d ~ "/" ~ item.path }}'
    owner: '{{ lidarr__srv._user }}'
    group: '{{ lidarr__srv._group }}'
    mode: '0750'
    state: 'directory'
  loop: '{{ query("community.general.filetree", lidarr__cfg._d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'directory'

- name: 'Config | filetree | set managed files'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ lidarr___app._var_d ~ "/" ~ item.path }}'
    owner: '{{ lidarr__srv._user }}'
    group: '{{ lidarr__srv._group }}'
    mode: '0640'
  loop: '{{ query("community.general.filetree", lidarr__cfg._d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ lidarr___app._var_d }}'
    file_type: 'any'
    hidden: true
    recurse: true
    excludes: 'MediaCover'  # Ignore MediaCover to prevent metadata deletion.
  register: lidarr__remote

- name: 'Config | filetree | remove unmanaged files and directories'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ lidarr__remote.files | sort(attribute="path", reverse=true) }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in
    (
      query("community.general.filetree", lidarr__cfg._d) |
      map(attribute='path') |
      map('regex_replace', '^', lidarr___app._var_d ~ "/") | list
    )
