---
###############################################################################
# Lidarr Install
###############################################################################
# Install specified version from github release.
#
# Args:
#   _lidarr_migrate_metadata: list of str - files and directories to migrate.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ lidarr_role_packages }}'
    apt_package_update_cache: true

- name: 'Install | Lidarr package {{ lidarr_service_version }}'
  when: not lidarr_service_force_config_only_enable
  ansible.builtin.include_role:
    name: 'r_pufky.deb.repo'
  vars:
    repo_release_owner: '{{ lidarr_role_repo_release_owner }}'
    repo_release_repo: '{{ lidarr_role_repo_release_repo }}'
    repo_release_tag: '{{ lidarr_service_version }}'
    repo_release_specifier: '{{ lidarr_role_repo_release_specifier }}'
    repo_release_asset: '{{ lidarr_role_repo_release_asset }}'
    repo_file_owner: '{{ lidarr_user }}'
    repo_file_group: '{{ lidarr_group }}'
    repo_extract_dir: '{{ lidarr_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ lidarr_role_repo_extract_symlink }}'
    repo_extract_migrate_files: '{{ _lidarr_migrate_metadata }}'
    repo_extract_delete_old_versions:
      '{{ lidarr_service_delete_old_versions_enable }}'
    repo_force_overwrite: '{{ lidarr_service_force_overwrite }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_extra_opts: '--strip-components=1'
