---
###############################################################################
# Install
###############################################################################
# Install specified version from github release. Use custom service according
# to Linux FHS standards:
#
# Type    | Perms               | Path
# --------|---------------------|-------
# Runtime | 0750/0640 SRV:SRV   | /var/opt/lidarr
#
# Installation notes:
# * *arr expects all configuration data to reside in a single directory: DB's,
#   config, and metadata.
#     Resolution: Place all config data within /var/opt/lidarr.
#
# Reference:
# * https://github.com/Lidarr/Lidarr/tree/develop/distribution/debian

- name: 'Install | filesystem | set system directories'
  ansible.builtin.file:
    path: '{{ lidarr___app._src_d }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Install | filesystem | set service directories'
  ansible.builtin.file:
    path: '{{ lidarr___app._var_d }}'
    owner: '{{ lidarr__srv._user }}'
    group: '{{ lidarr__srv._group }}'
    mode: '0755'
    state: 'directory'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ lidarr___packages }}'
    apt_srv_package_update_cache: true

- name: 'Install | filesystem | find previous installations'
  ansible.builtin.find:
    paths: '{{ lidarr___app._src_d }}'
    file_type: 'directory'
    recurse: false
    excludes:
      - '{{ lidarr__cfg._version }}'
  register: lidarr__cmd

- name: 'Install | filesystem | remove previous installations'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ lidarr__cmd.files }}'
  loop_control:
    label: '{{ item.path }}'

- name: 'Install | url | 🗘 Lidarr (~1 minute) 🗘'
  when: not (molecule_flg_inject | default(false))
  ansible.builtin.get_url:
    url: '{{ lidarr__cfg._url }}'
    dest: '{{ "/tmp/" ~ lidarr__cfg._package }}'
    force: false
    owner: 'root'
    group: 'root'
    mode: '0644'
    headers:
      Authorization: '{{ lidarr__srv._token | default(omit) }}'
  register: lidarr__cmd
  until: lidarr__cmd is succeeded

- name: '{{ "Install | filesystem | set " ~ lidarr__cfg._app_d }}'
  ansible.builtin.file:
    path: '{{ lidarr__cfg._app_d }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Install | filesystem | unpack Lidarr'
  ansible.builtin.unarchive:
    creates: '{{ lidarr__cfg._app_d ~ "/Lidarr" }}'
    src: '{{ "/tmp/" ~ lidarr__cfg._package }}'
    remote_src: true
    dest: '{{ lidarr__cfg._app_d }}'
    owner: 'root'
    group: 'root'
    mode: 'a-st'
    extra_opts: ['--strip-components=1']

- name: '{{ "Install | filesystem | set " ~ lidarr___app._service }}'
  ansible.builtin.template:
    src: 'systemd/lidarr.service.j2'
    dest: '{{ lidarr___app._service }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
