---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    lidarr__srv: "{{ lidarr___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _user=lidarr_srv_user,
        _group=lidarr_srv_group,
      ) }}"
    lidarr__cfg: "{{ lidarr___app | r_pufky.data.v3(

        _version=lidarr_srv_version,
        _package=(
          'Lidarr.master.' ~ lidarr_srv_version[1:] ~ '.linux-core-x64.tar.gz'
        ),
        _app='/opt/lidarr/src/' ~ lidarr_srv_version,
        _url=(
          lidarr___repo_url ~ lidarr_srv_version ~ '/' ~
          'Lidarr.master.' ~ lidarr_srv_version[1:] ~ '.linux-core-x64.tar.gz'
        ),
        _dir=lidarr_cfg_dir | regex_replace('\\/$', ''),
        _backup_dir=lidarr_cfg_backup_dir | regex_replace('\\/$', ''),
        _backup_metadata=lidarr_cfg_backup_metadata,
      ) }}"

- name: 'Prep | assert | backup enabled and location defined'
  when: lidarr_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - lidarr__cfg._backup_dir | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      lidarr_flg_backup: {{ lidarr_flg_backup }}
      lidarr_cfg_backup_dir: {{ lidarr__cfg._backup_dir }}

- name: 'Prep | assert | restore enabled and location defined'
  when: lidarr_flg_restore
  ansible.builtin.assert:
    quiet: true
    that:
      - lidarr__cfg._backup_dir | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      lidarr_flg_restore: {{ lidarr_flg_restore }}
      lidarr_cfg_backup_dir: {{ lidarr__cfg._backup_dir }}

- name: 'Prep | assert | config enabled and source defined'
  when: lidarr_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - lidarr__cfg._dir | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      lidarr_flg_config: {{ lidarr_flg_config }}
      lidarr_cfg_dir: {{ lidarr__cfg._dir }}

- name: '{{ "Prep | account | query user " ~ lidarr__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ lidarr__srv._user }}'
  failed_when: false
  register: lidarr__cfg_check
  changed_when: lidarr__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ lidarr__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ lidarr__srv._group }}'
  failed_when: false
  register: lidarr__group_check
  changed_when: lidarr__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ lidarr__srv._group }}'
  when: lidarr__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ lidarr___group.gid }}'
    name: '{{ lidarr___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ lidarr__srv._user }}'
  when: lidarr__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ lidarr___user.name }}'
    group: '{{ lidarr___user.group }}'
    uid: '{{ lidarr___user.uid }}'
    shell: '{{ lidarr___user.shell }}'
    home: '{{ lidarr___user.home }}'
    create_home: '{{ lidarr___user.create_home }}'
    password: '{{ lidarr___user.password }}'
    password_lock: '{{ lidarr___user.password_lock }}'
    update_password: '{{ lidarr___user.update_password }}'
    expires: '{{ lidarr___user.expires }}'
    system: '{{ lidarr___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ lidarr__srv._user }}'
  ansible.builtin.user:
    name: '{{ lidarr__srv._user }}'
  check_mode: true
  changed_when: false
  register: lidarr__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    lidarr__cfg: "{{ lidarr__cfg | r_pufky.data.v3(

        _uid=lidarr__cfg_query.uid,
        _gid=lidarr__cfg_query.group,
      ) }}"

- name: 'Prep | systemd | stop lidarr.service'
  ansible.builtin.systemd:
    name: 'lidarr.service'
    state: 'stopped'
  failed_when: false
