---
###############################################################################
# Lidarr Prep
###############################################################################
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | assert database requirements'
  when: _lidarr_cfg_database_type.raw == 'postgres'
  ansible.builtin.assert:
    quiet: true
    that:
      - _lidarr_cfg_database_host.raw | length > 0
      - _lidarr_cfg_database_port.raw > 0
      - _lidarr_cfg_database_user.raw | length > 0
      - _lidarr_cfg_database_password.raw | length > 0
      - _lidarr_cfg_database_main.raw | length > 0
      - _lidarr_cfg_database_log.raw | length > 0
    fail_msg: >
      ✘ lidarr_cfg_database_type=postgres requires all options set.

          lidarr_cfg_database_host: '{{ _lidarr_cfg_database_host.raw }}'
          lidarr_cfg_database_port: '{{ _lidarr_cfg_database_port.raw }}'
          lidarr_cfg_database_user: '{{ _lidarr_cfg_database_user.raw }}'
      lidarr_cfg_database_password: '{{ _lidarr_cfg_database_password.raw }}'
          lidarr_cfg_database_main: '{{ _lidarr_cfg_database_main.raw }}'
           lidarr_cfg_database_log: '{{ _lidarr_cfg_database_log.raw }}'

- name: 'Prep | assert SSL requirements'
  when: _lidarr_cfg_enable_ssl.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _lidarr_cfg_ssl_cert_path.raw | length > 0
    fail_msg: >
      ✘ lidarr_cfg_enable_ssl=true requires
      lidarr_cfg_ssl_cert_path set.

      lidarr_cfg_ssl_cert_path: '{{ _lidarr_cfg_ssl_cert_path.raw }}'

- name: 'Prep | assert update script requirements'
  when: not _lidarr_cfg_update_mechanism.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _lidarr_cfg_update_script_path.raw | length > 0
    fail_msg: >
      ✘ lidarr_cfg_update_mechanism=false requires
      lidarr_cfg_update_script_path set.

      lidarr_cfg_update_script_path: '{{ _lidarr_cfg_update_script_path.raw }}'

- name: 'Prep | manage users'
  when: _lidarr_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ lidarr_role_user }}'
    users_role_group: '{{ lidarr_role_group }}'

- name: 'Prep | enumerate system user {{ _lidarr_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _lidarr_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _lidarr_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _lidarr_srv_user: '{{
        _lidarr_srv_user |
        combine({"role_uid": _lidarr_srv_user_query.uid})
      }}'
    _lidarr_srv_group: '{{
        _lidarr_srv_group |
        combine({"role_gid": _lidarr_srv_user_query.group})
      }}'

- name: 'Prep | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'lidarr.service'
