---
###############################################################################
# Lidarr Handlers
###############################################################################

- name: 'Handlers | restart lidarr'
  ansible.builtin.systemd:
    name: 'lidarr'
    enabled: true
    state: 'restarted'
