---
###############################################################################
# Lidarr Service Config (config.xml)
###############################################################################
# Externally stored service configuration for Lidarr to successfully start.
# Additional settings are stored in the DB. WebUI locations are headers but all
# values are stored within config.xml.
#
# PascalCase: lidarr_cfg_bind_address > BindAddress.
#
# Documented usage here reflect code, installer, and WebUI analysis. These may
# change over time and should be re-validated from time to time.

###############################################################################
# Settings > General > Host
###############################################################################

# Bind Lidarr service to specified interface.
#
# Values:
#           *: Bind to all available interfaces (default).
#        {IP}: Bind to valid IP address ('127.0.0.1', '::', etc).
#   localhost: Bind to localhost.
#
# Default: '*'.
lidarr_cfg_bind_address: '*'

# HTTP port. Default: 8686.
lidarr_cfg_port: 8686

# URL base for reverse proxy support. Default: '' (disabled).
lidarr_cfg_url_base: ''

# Lidarr application name for browser tab and syslog logs. Default: 'Lidarr'.
lidarr_cfg_instance_name: 'Lidarr'

# Enable SSL? Default: False.
lidarr_cfg_enable_ssl: false

# HTTPS port. Default: 6868.
lidarr_cfg_ssl_port: 6868

# Path to PFX certificate.
#
# Sourced from ansible controller; automatically placed in
# lidarr_srv_config_dir/lidarr.pfx with correct permissions. Lidarr will be
# automatically configured to use the installed location.
#
# lidarr_cfg_ssl_cert_path: 'host_vars/nzb.example.com/data/my_cert.pfx'
#
# Default: '' (disabled).
lidarr_cfg_ssl_cert_path: ''

# PFX certificate password.
#
# WARNING: this is stored unencrypted in Lidarr's config.xml.
#
# Default: '' (no password).
lidarr_cfg_ssl_cert_password: ''

###############################################################################
# Settings > General > Security
###############################################################################

# Authentication method for user access.
#
# Special Case:
#   * New installs REQUIRE 'none' to create a login user; authentication can be
#     toggled on after the user exists in the database . Suggest running
#     initial role application temporarily disabling this option:
#
#     ansible-playbook lidarr.yml -e 'lidarr_cfg_authentication_method=none'
#
# Values:
#   external: Force user creation and auth selection WebUI (first run only).
#             basic or forms must be used after first run.
#      basic: Browser pop-up for credentials.
#      forms: Login page for credentials (use for password managers) (default).
#
# Default: 'forms'.
#
# Reference:
# * https://wiki.servarr.com/lidarr/faq#help-i-have-locked-myself-out
lidarr_cfg_authentication_method: 'forms'

# Require authentication for all addresses?
#
# Always required for non-local connections. Disabling this will allow local
# addresses access WITHOUT authentication.
#
# Default: False.
lidarr_cfg_authentication_required: false

# Lidarr API key.
#
# Explicitly specify your key for consistent role application. Autogenerated
# value is deterministic.
#
# Special Case:
#   '': Random 32 character alphanumeric hash
#
# Default: '{RANDOM}' (insecure idempotent API key based on hostname).
lidarr_cfg_api_key:
  '{{ inventory_hostname | md5 | truncate(32, true, "") }}'

###############################################################################
# Settings > General > Logging
###############################################################################

# Lidarr service log level.
#
# Values:
#    info: Standard logging (default).
#   debug: Log additional information.
#   trace: Log everything.
#
# Default: 'info'.
lidarr_cfg_log_level: 'info'

# Max log size before archiving (MB). Default: 1.
lidarr_cfg_log_size_limit: 1

###############################################################################
# Settings > General > Analytics
###############################################################################

# Send usage and errors to Lidarr developers?
#
# Includes browser, Lidarr WebUI pages, error reporting, OS information, and
# runtime versions. Used to prioritize features and bug fixes.
#
# Default: False.
lidarr_cfg_analytics_enabled: false

###############################################################################
# Settings > General > Updates (config.xml)
###############################################################################

# Lidarr update branch to use.
#
# Values:
#    master: Stable release (default).
#   develop: Beta/unstable - bleeding edge. may NOT be able to go back to main
#            after switching to this branch.  It is released as soon as code is
#            committed and passes all automated tests. This build may have not
#            been used by us or other users yet. There is no guarantee that it
#            will even run in some cases. This branch is only recommended for
#            advanced users. Issues and self investigation are expected in this
#            branch. Use this branch only if you know what you are doing and
#            are willing to get your hands dirty to recover a failed update.
#            This version is updated immediately.
#
# Default: 'master'.
#
# Reference:
# * https://wiki.servarr.com/lidarr/faq#how-do-i-update-lidarr
lidarr_cfg_branch: 'master'

# Automatically download and install updates? Default: False.
lidarr_cfg_update_automatically: false

# Automatic update mechanism.
#
# Non-docker installs only support BuiltIn or Script.
#
# Values:
#    True: Use internal update mechanism (BuiltIn) (default).
#   False: Use external update script (Script); requires
#          lidarr_cfg_update_script_path.
#
# Default: True.
#
# Reference:
# * https://wiki.servarr.com/lidarr/settings#updates
lidarr_cfg_update_mechanism: true

# Docker, External, Built-in, Script

# Custom script path for updates.
#
# Script should take an extracted update package and handle the remainder of
# the update process.
#
# Sourced from ansible controller; automatically placed in
# lidarr_srv_config_dir/update_script with correct permissions. Lidarr will
# be automatically configured to use the installed location.
#
# lidarr_cfg_update_script_path: 'host_vars/nzb.example.com/data/script.sh'
#
# Default: '' (disabled).
lidarr_cfg_update_script_path: ''

###############################################################################
# Settings > General > Startup (config.xml)
###############################################################################

# Launch browser on startup?
#
# Only use when not running as a service. Removed entirely from the WebUI but
# used to be in settings > general > startup.
#
# Default: False.
lidarr_cfg_launch_browser: false

###############################################################################
# Settings > UI > Style
###############################################################################

# Lidarr WebUI theme.
#
# Values:
#    auto: Use OS theme (default).
#   light: Light mode.
#    dark: Dark mode.
#
# Default: 'auto'.
lidarr_cfg_theme: 'auto'
