---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | cache 2.14.5.4836'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache 2.14.5.4836'
        test_dest: 'Lidarr.master.2.14.5.4836.linux-core-x64.tar.gz'
        test_url: '{{
            "https://github.com/Lidarr/Lidarr/releases/download/" ~
            "v2.14.5.4836/" ~
            "Lidarr.master.2.14.5.4836.linux-core-x64.tar.gz"
          }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'lidarr-debian-13-user_data'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 5555
        group: 5555
        mode: '0755'
        state: 'directory'
