---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.lidarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.lidarr'

- name: 'Converge | toggle updates'
  hosts: 'lidarr-debian-13-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle updates | apply r_pufky.srv.lidarr'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.lidarr'
      vars:
        lidarr_cfg_update_mechanism: true
