---
- name: 'Update mechanisms | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Update mechanisms | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Update mechanisms | prepare | create cache'

    - name: 'Update mechanisms | prepare | cache 2.9.6.4552'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Update mechanisms | prepare | cache 2.9.6.4552'
        test_dest: 'Lidarr.master.2.9.6.4552.linux-core-x64.tar.gz'
        test_url: '{{
            "https://github.com/Lidarr/Lidarr/releases/download/" ~
            "v2.9.6.4552/" ~
            "Lidarr.master.2.9.6.4552.linux-core-x64.tar.gz"
          }}'
        test_mode: '0640'
